import{resolveSpotifyContent}from"./spotify.js";
const WORKSPACE_KEY="painel-da-mirna:workspace:v3",TOKEN_KEY="painel-da-mirna:cloud-token:v1",LOG_KEY="painel-da-mirna:diagnostics-log:v1";
let root,running=false,results={};
const safeJson=(value,fallback=null)=>{try{return JSON.parse(value);}catch{return fallback;}};
const esc=value=>String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
const workspace=()=>safeJson(localStorage.getItem(WORKSPACE_KEY),{})||{};
const token=()=>Boolean(localStorage.getItem(TOKEN_KEY)?.trim());
function addLog(message,level="info"){const rows=safeJson(localStorage.getItem(LOG_KEY),[]);localStorage.setItem(LOG_KEY,JSON.stringify([{at:new Date().toISOString(),message,level},...(Array.isArray(rows)?rows:[])].slice(0,12)));renderLog();}
function renderLog(){const list=root?.querySelector("#diag-log");if(!list)return;const rows=safeJson(localStorage.getItem(LOG_KEY),[]);list.innerHTML=rows?.length?rows.map(row=>`<div class="diag-log-row"><time>${new Intl.DateTimeFormat("pt-BR",{day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit"}).format(new Date(row.at))}</time><span>${esc(row.message)}</span></div>`).join(""):'<p class="diag-empty">Nenhum alerta registrado.</p>';}
function card(id,name,icon,state,summary,detail,actions=[]){return{id,name,icon,state,summary,detail,actions};}
async function health(){try{const response=await fetch("/api/health",{cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);return await response.json();}catch(error){return{ok:false,error:String(error?.message||error)};}}
async function weather(){try{const response=await fetch(`/api/weather?city=${encodeURIComponent("Marechal Cândido Rondon, Paraná")}`,{cache:"no-store"});if(!response.ok)throw new Error(`HTTP ${response.status}`);return{ok:true,data:await response.json()};}catch(error){return{ok:false,error:String(error?.message||error)};}}
function calendarCard(){const api=window.__mirnaCalendarV6,rows=api?.getConnections?.()||[],events=(workspace().events||[]).filter(event=>["google-calendar-v6","google-calendar-v7"].includes(event.autoSource)).length,errors=rows.filter(item=>item.lastStatus==="error");if(!api)return card("calendar","Google Agenda","◫","error","Módulo não iniciou","Recarregue os módulos do aplicativo.",["reload"]);if(!rows.length)return card("calendar","Google Agenda","◫","warning","Nenhuma agenda conectada","Cole o Endereço secreto em formato iCal.",["calendar-open","calendar-sync"]);if(errors.length)return card("calendar","Google Agenda","◫","warning",`${rows.length-errors.length}/${rows.length} conexões operando`,`${events} evento(s) preservado(s); ${errors.length} conexão(ões) precisa(m) de atenção.`,["calendar-open","calendar-sync"]);return card("calendar","Google Agenda","◫","ok",`${rows.length} agenda(s) conectada(s)`,`${events} evento(s) importado(s); atualização automática ativa.`,["calendar-open","calendar-sync"]);}
function modulesCard(){const checks=[["Planejador",window.__mirnaWorkspace],["Dados",window.__mirnaDataHub],["Ateliê",window.__mirnaAtelier],["Navbar",document.querySelector(".mirna-sidebar-v7")]],missing=checks.filter(([,ready])=>!ready).map(([name])=>name);return missing.length?card("modules","Aplicativo","✦","warning",`${checks.length-missing.length}/${checks.length} módulos iniciados`,`Aguardando: ${missing.join(", ")}.`,["reload"]):card("modules","Aplicativo","✦","ok","Todos os módulos iniciados","Planejador, dados, Ateliê e navegação responderam.",["reload"]);}
function spotifyCard(){const resolved=resolveSpotifyContent(workspace().spotify?.contentUrl);return resolved?.kind==="embed"?card("spotify","Spotify","♫","ok","Playlist configurada","O player está pronto no painel.",["spotify-open"]):card("spotify","Spotify","♫","warning","Nenhuma playlist escolhida","Abra a seção e carregue uma playlist.",["spotify-open"]);}
async function collect(forceCalendar=false){if(forceCalendar)await window.__mirnaCalendarV6?.syncNow?.();const[h,w]=await Promise.all([health(),weather()]);return[modulesCard(),calendarCard(),h.database?card("database","Neon","◉",token()?"ok":"warning","Banco disponível",token()?"Token privado encontrado neste navegador.":"Banco pronto; falta o token privado neste navegador.",["files-open"]):card("database","Neon","◉","error","Banco indisponível","A conexão do banco não respondeu.",["refresh"]),h.files?card("files","Arquivos","▣",token()?"ok":"warning","Vercel Blob disponível",token()?"CRUD na nuvem habilitado.":"Arquivos locais funcionam; nuvem aguarda o token.",["files-open"]):card("files","Arquivos","▣","error","Blob indisponível","Uploads na nuvem não estão disponíveis.",["files-open"]),spotifyCard(),w.ok?card("weather","Clima","☀","ok",`${w.data.current?.temperature??"—"}° agora`,`Sensação ${w.data.current?.feelsLike??"—"}° · chuva ${w.data.today?.rainChance??0}%.`,["refresh"]):card("weather","Clima","☀","warning","Previsão não respondeu",w.error||"Tente novamente.",["refresh"]),h.ok?card("backend","Servidor","☁","ok","APIs respondendo","Agenda, estado, arquivos e clima podem ser consultados.",["refresh"]):card("backend","Servidor","☁","error","API indisponível",h.error||"A Vercel não respondeu.",["refresh"])];}
const labels={refresh:"Testar novamente",reload:"Recarregar módulos","calendar-open":"Abrir configuração","calendar-sync":"Sincronizar","files-open":"Abrir arquivos","spotify-open":"Abrir Spotify"};
function render(){const grid=root?.querySelector("#diag-grid");if(!grid)return;grid.innerHTML=Object.values(results).map(item=>`<article class="diag-card" data-state="${item.state}"><div class="diag-card-head"><span class="diag-icon">${item.icon}</span><span class="diag-state">${item.state==="ok"?"✓ Operando":item.state==="warning"?"! Atenção":"× Falha"}</span></div><h3>${esc(item.name)}</h3><strong>${esc(item.summary)}</strong><p>${esc(item.detail)}</p><div class="diag-actions">${item.actions.map(action=>`<button type="button" data-diag-action="${action}">${labels[action]||action}</button>`).join("")}</div></article>`).join("");}
async function refresh(force=false){if(running)return false;running=true;const button=root?.querySelector("#diag-refresh");button?.setAttribute("disabled","");if(button)button.textContent="Testando…";try{const rows=await collect(force);results=Object.fromEntries(rows.map(item=>[item.id,item]));render();const alerts=rows.filter(item=>item.state!=="ok").length;root.querySelector("#diag-summary").textContent=alerts?`${rows.length-alerts}/${rows.length} conexões operando`:"Tudo operando normalmente";addLog(alerts?`Diagnóstico concluído com ${alerts} ponto(s) de atenção.`:"Diagnóstico concluído sem falhas.",alerts?"warning":"ok");return!alerts;}finally{running=false;button?.removeAttribute("disabled");if(button)button.textContent="↻ Testar tudo";}}
function go(selector){document.querySelector(selector)?.scrollIntoView({behavior:"smooth",block:"start"});}
async function action(name){if(name==="refresh")return refresh();if(name==="reload")return location.reload();if(name==="calendar-open")return go("#hub-calendar-card");if(name==="calendar-sync"){await window.__mirnaCalendarV6?.syncNow?.();return refresh();}if(name==="files-open")return go("#hub-files-card");if(name==="spotify-open")return go("#spotify");}
function styles(){if(document.querySelector("#diagnostics-v1-style"))return;const style=document.createElement("style");style.id="diagnostics-v1-style";style.textContent='.diagnostics-shell{max-width:1180px;margin:44px auto 20px;scroll-margin-top:92px}.diag-head{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:16px}.diag-head h2{margin:4px 0 6px;font:700 clamp(1.8rem,3vw,2.7rem)/1.05 Georgia,serif}.diag-head p{margin:0;color:var(--muted,#756a70)}.diag-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.diag-card{display:flex;flex-direction:column;min-height:205px;padding:17px;border:1px solid var(--line,rgba(72,54,63,.12));border-radius:20px;background:var(--surface,#fffdfb);box-shadow:var(--shadow-soft,0 12px 34px rgba(73,49,61,.06))}.diag-card[data-state="ok"]{--diag:#629071}.diag-card[data-state="warning"]{--diag:#b98c45}.diag-card[data-state="error"]{--diag:#b45b68}.diag-card-head{display:flex;justify-content:space-between;align-items:center}.diag-icon{display:grid;place-items:center;width:38px;height:38px;border-radius:13px;background:color-mix(in srgb,var(--diag) 13%,transparent)}.diag-state{color:var(--diag);font-size:.67rem;font-weight:850;text-transform:uppercase}.diag-card h3{margin:15px 0 5px}.diag-card>strong{font-size:.87rem}.diag-card p{margin:7px 0 16px;color:var(--muted,#756a70);font-size:.78rem;line-height:1.45}.diag-actions{display:flex;flex-wrap:wrap;gap:7px;margin-top:auto}.diag-actions button{border:1px solid var(--line,rgba(72,54,63,.12));border-radius:10px;background:transparent;color:inherit;padding:7px 9px;font:inherit;font-size:.72rem;font-weight:750;cursor:pointer}.diag-log{margin-top:12px;border:1px solid var(--line,rgba(72,54,63,.1));border-radius:17px;padding:13px}.diag-log-list{display:grid;gap:7px;margin-top:11px}.diag-log-row{display:grid;grid-template-columns:96px 1fr;gap:10px;color:var(--muted,#756a70);font-size:.74rem}.diag-summary{font-size:.78rem;font-weight:800;color:var(--muted,#756a70)}@media(max-width:1050px){.diag-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:650px){.diag-head{align-items:flex-start;flex-direction:column}.diag-grid{grid-template-columns:1fr}.diag-card{min-height:0}.diag-log-row{grid-template-columns:1fr}}';document.head.append(style);}
function nav(){const scroll=document.querySelector(".mirna-sidebar-v7 .ms7-scroll");if(scroll&&!document.querySelector('[data-ms7-target="system-diagnostics"]')){const group=document.createElement("nav");group.className="ms7-group";group.innerHTML='<div class="ms7-group-title">Conexões</div><a class="ms7-link" href="#system-diagnostics" data-ms7-target="system-diagnostics"><span class="ms7-icon">◉</span><span class="ms7-label">Diagnóstico</span></a>';scroll.prepend(group);}}
function build(){styles();root=document.createElement("section");root.id="system-diagnostics";root.className="diagnostics-shell";root.innerHTML='<div class="diag-head"><div><p class="eyebrow">Central de conexões</p><h2>Diagnóstico do Ateliê</h2><p>Veja o que está conectado e teste cada serviço sem adivinhação.</p></div><div><span class="diag-summary" id="diag-summary">Preparando testes…</span> <button class="button button-ghost" id="diag-refresh" type="button">↻ Testar tudo</button></div></div><div class="diag-grid" id="diag-grid"></div><details class="diag-log"><summary>Histórico recente</summary><div class="diag-log-list" id="diag-log"></div></details>';const hub=document.querySelector("#mirna-data-hub");hub?hub.before(root):document.querySelector("#workspace-root")?.append(root);root.querySelector("#diag-refresh")?.addEventListener("click",()=>refresh(true));root.addEventListener("click",event=>{const button=event.target.closest("[data-diag-action]");if(button)action(button.dataset.diagAction);});renderLog();nav();}
async function init(){const started=Date.now();while((!document.querySelector("#workspace-root")||!document.querySelector("#mirna-data-hub"))&&Date.now()-started<16000)await new Promise(resolve=>setTimeout(resolve,100));build();await refresh();window.addEventListener("online",()=>refresh());window.__mirnaDiagnostics={refresh,results:()=>structuredClone(results),open:()=>go("#system-diagnostics")};}
init().catch(error=>addLog(`Diagnóstico não iniciou: ${error?.message||error}`,"warning"));
