const RELEASE="15.0";
const STORE_KEY="painel-da-mirna:teacher:v1";
const ATELIER_KEY="atelie-da-mirna:v3";
const VIEW_KEY="painel-da-mirna:aulas-view:v1";
const $=(selector,scope=document)=>scope.querySelector(selector);
const $$=(selector,scope=document)=>[...scope.querySelectorAll(selector)];
const safe=(value,fallback)=>{try{return JSON.parse(value);}catch{return fallback;}};
const esc=value=>String(value??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
let activeView=sessionStorage.getItem(VIEW_KEY)||"overview";
let productionState;

function teacherState(){const value=safe(localStorage.getItem(STORE_KEY),{});return{groups:Array.isArray(value.groups)?value.groups:[],students:Array.isArray(value.students)?value.students:[],lessons:Array.isArray(value.lessons)?value.lessons:[],attendance:Array.isArray(value.attendance)?value.attendance:[],observations:Array.isArray(value.observations)?value.observations:[]};}
function atelierState(){const value=safe(localStorage.getItem(ATELIER_KEY),{});return{...value,productions:Array.isArray(value.productions)?value.productions:[]};}
function saveAtelier(){productionState.updatedAt=new Date().toISOString();localStorage.setItem(ATELIER_KEY,JSON.stringify(productionState));window.dispatchEvent(new StorageEvent("storage",{key:ATELIER_KEY,newValue:JSON.stringify(productionState)}));}
function uid(prefix){return`${prefix}-${crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`}`;}
function toast(message){const element=$("#dance-toast");if(!element)return;element.textContent=message;element.classList.add("show");setTimeout(()=>element.classList.remove("show"),2500);}
function todayText(){return new Intl.DateTimeFormat("pt-BR",{weekday:"long",day:"2-digit",month:"long"}).format(new Date());}
function viewTitle(view){return{overview:["Visão geral","Próximas aulas, pendências e atalhos."],routines:["Rotinas","Horários, vigência, recessos e geração automática."],classes:["Aulas","Planejamento e histórico das aulas."],people:["Turmas e alunas","Cadastros e pontos de atenção."],attendance:["Chamada","Presença, faltas e justificativas."],evolution:["Evolução","Observações pedagógicas e acompanhamento."],productions:["Produções","Coreografias, festivais e apresentações."]}[view]||["Aulas & Dança",""];}
function panelKind(panel){const title=$("h4",panel)?.textContent.trim().toLowerCase()||"";if(panel.id==="teacher-recurring")return"routines";if(title==="turmas"||title==="alunas")return"people";if(title.includes("planejamento de aula"))return"classes";if(title==="chamada")return"attendance";if(title.includes("observação pedagógica"))return"evolution";return"other";}
function ensureOverview(){let overview=$("#dance-overview");if(overview)return overview;overview=document.createElement("section");overview.id="dance-overview";overview.className="dance-overview";const workflow=$("#teacher-workflow");workflow?.prepend(overview);return overview;}
function renderOverview(){const state=teacherState(),overview=ensureOverview();const today=new Date().toISOString().slice(0,10);const upcoming=state.lessons.filter(item=>item.date>=today&&item.status!=="cancelled").sort((a,b)=>`${a.date}${a.startTime||""}`.localeCompare(`${b.date}${b.startTime||""}`));const needs=upcoming.filter(item=>!item.objective||!item.structure);const next=upcoming[0];overview.innerHTML=`<div class="dance-section-title"><div><h2>Visão geral</h2><p>O essencial da vida de professora, sem excesso de informação.</p></div></div><div class="tf-summary"><div class="tf-metric"><strong>${state.groups.length}</strong><small>turmas</small></div><div class="tf-metric"><strong>${state.students.length}</strong><small>alunas</small></div><div class="tf-metric"><strong>${upcoming.length}</strong><small>próximas aulas</small></div><div class="tf-metric"><strong>${needs.length}</strong><small>pedem preparo</small></div></div>${next?`<article class="dance-panel"><h3>Próxima aula</h3><div class="tf-row"><div><strong>${esc(next.title)}</strong><small>${esc(next.date.split("-").reverse().join("/"))}${next.startTime?` · ${esc(next.startTime)}`:""}${next.objective?` · ${esc(next.objective)}`:" · objetivo pendente"}</small></div><button class="tf-btn secondary" type="button" data-dance-jump="classes">Abrir aulas</button></div></article>`:'<article class="dance-panel"><h3>Nenhuma aula futura</h3><p>Configure uma rotina ou crie uma aula manualmente.</p></article>'}<div class="dance-overview-actions"><button class="dance-action" type="button" data-dance-jump="routines"><strong>Organizar rotinas</strong><small>Horários, vigência e recessos.</small></button><button class="dance-action" type="button" data-dance-jump="classes"><strong>Preparar aulas</strong><small>Objetivo, sequência, música e materiais.</small></button><button class="dance-action" type="button" data-dance-jump="attendance"><strong>Fazer chamada</strong><small>Presença e justificativas por turma.</small></button></div>`;}
function renderProductions(){let section=$("#dance-productions");if(!section){section=document.createElement("section");section.id="dance-productions";$("#teacher-workflow")?.append(section);}productionState=atelierState();section.innerHTML=`<div class="dance-section-title"><div><h2>Produções</h2><p>Coreografias, festivais, apresentações e ensaios.</p></div></div><div class="dance-production-grid"><article class="dance-panel"><h3>Produções em andamento</h3><div class="dance-production-list">${productionState.productions.length?productionState.productions.map(item=>`<div class="dance-production-item"><div><strong>${esc(item.title)}</strong><small>${esc(item.kind||"Produção")}${item.date?` · ${esc(item.date.split("-").reverse().join("/"))}`:""} · ${esc(item.status||"Ideia")}</small>${item.note?`<small>${esc(item.note)}</small>`:""}</div><button class="tf-btn secondary" type="button" data-production-remove="${esc(item.id)}">Excluir</button></div>`).join(""):'<div class="tf-empty">Nenhuma produção cadastrada.</div>'}</div></article><article class="dance-panel"><h3>Nova produção</h3><form class="dance-form" id="dance-production-form"><input name="title" placeholder="Nome do projeto" required><select name="kind"><option>Coreografia</option><option>Festival</option><option>Apresentação</option><option>Ensaio</option></select><input name="date" type="date"><select name="status"><option>Ideia</option><option>Planejamento</option><option>Em ensaio</option><option>Pronto</option></select><textarea name="note" placeholder="Música, figurino, transporte, inscrições…"></textarea><button class="dance-primary" type="submit">Adicionar produção</button></form></article></div>`;const form=$("#dance-production-form");form.onsubmit=event=>{event.preventDefault();const data=Object.fromEntries(new FormData(form).entries());productionState.productions.push({id:uid("production"),...data});saveAtelier();renderProductions();toast("Produção adicionada.");};section.onclick=event=>{const button=event.target.closest("[data-production-remove]");if(!button)return;productionState.productions=productionState.productions.filter(item=>item.id!==button.dataset.productionRemove);saveAtelier();renderProductions();toast("Produção removida.");};}
function showView(view){activeView=view;sessionStorage.setItem(VIEW_KEY,view);$$('[data-dance-view]').forEach(button=>button.setAttribute("aria-selected",String(button.dataset.danceView===view)));const [title,copy]=viewTitle(view);const hero=$(".dance-hero");hero.querySelector("h1").textContent=title;hero.querySelector("p").textContent=copy;renderOverview();renderProductions();const overview=$("#dance-overview"),productions=$("#dance-productions");overview.hidden=view!=="overview";productions.hidden=view!=="productions";$$('#teacher-workflow .tf-panel').forEach(panel=>{panel.hidden=panelKind(panel)!==view;});const summary=$("#teacher-workflow > .tf-summary");if(summary)summary.hidden=true;window.scrollTo({top:0,behavior:"smooth"});}
function bindNavigation(){document.addEventListener("click",event=>{const button=event.target.closest("[data-dance-view],[data-dance-jump]");if(!button)return;showView(button.dataset.danceView||button.dataset.danceJump);});}
async function waitFor(test,timeout=8000){const start=Date.now();while(Date.now()-start<timeout){if(test())return true;await new Promise(resolve=>setTimeout(resolve,80));}return false;}
async function loadModules(){await import(`/teacher-migration-v1.js?release=${RELEASE}`);await import(`/teacher-workflow-v1.js?release=${RELEASE}`);if(!await waitFor(()=>window.__mirnaTeacher&&$("#teacher-workflow")))throw new Error("A central pedagógica não terminou de carregar.");await import(`/teacher-recurring-v1.js?release=${RELEASE}`);await waitFor(()=>window.__mirnaTeacherRecurring&&$("#teacher-recurring"),6000);}
async function init(){$("#dance-today").textContent=todayText();bindNavigation();try{await loadModules();$("#dance-loading")?.remove();renderOverview();renderProductions();showView(activeView);$("#dance-status").textContent="Central pronta";}catch(error){$("#dance-status").textContent="Atenção";$("#dance-loading").textContent=error.message||"Não foi possível abrir a central.";}}
init();
